box::use(tibble)

#' all possible columns for standardized translation data (v2 = babelonplus)
#' @export
col_order <- c(
  "subject_id", "predicate_id", "source_language", "source_value",
  "translation_language", "translation_value", "translator",
  "translator_expertise", "translation_date", "translation_provider",
  "translation_status", "translation_confidence", "confidence_details",
  "reviewer", "reviewer_expertise", "comment", "status_history",
  "backtranslation", "backtranslator", "backtranslation_date",
  "source", "source_version", "synonym_type", "match_id"
)

# captures required columns and establishes set order for reproducibility
match_cols <- tibble$tribble(
  ~ type, ~ col_nm,
  "uri", "subject_id",
  "uri", "predicate_id",
  "string", "source_language",
  "string", "source_value",
  "string", "translation_language",
  "string", "translation_value",
  "uri/string", "translator"
)


#' Calculate `match_id`
#'
#' `match_id` is a unique identifier for core columns of babelon & babelonplus
#' translation records. It is generated by concatenating core column data
#' followed by md5 hashing, with the final hash truncated to 15 characters. This
#' ensures that the same set of core date will always produce the same
#' `match_id`.
#'
#' @param .df A babelon- or babelonplus-compatible data.frame.
#' @returns The input data frame with an additional `match_id` column containing
#' a 15-character ID.
#'
#' @section Core Columns:
#' The following columns are currently considered among the core set and are
#' used to generate `match_id`:
#' `r paste0("* ", match_cols, collapse = "\n")`
#'
#' @md
#' @export
calc_match_id <- function(.df) {
  box::use(
    digest, dplyr, purrr, stringr, tidyr,
    ./general
  )

  # cols to expand to URIs
  uri_cols <- dplyr$filter(
    match_cols,
    stringr$str_detect(.data$type, "uri")
  )$col_nm

  match_df <- dplyr$select(.df, dplyr$all_of(match_cols$col_nm)) |>
    dplyr$mutate(
      dplyr$across(dplyr$all_of(uri_cols), ~ general$uri_curie(.x, to = "uri"))
    )

  missing <- purrr::pmap_lgl(match_df, function(...) { any(is.na(c(...))) })
  if (any(missing)) {
    n <- sum(missing)
    if (n > 10) {
      n_list <- paste0(c(which(missing)[1:10], "..."), collapse = ", ")
    } else {
      n_list <- paste0(which(missing), collapse = ", ")
    }
    stop(
      "Cannot calculate match_id: core columns contain NA values in ",
      n,
      "rows:\n  ",
      n_list
    )
  }

  match_id <- purrr$pmap_chr(
    match_df,
    function(...) {
      match_str <- paste0(c(...), collapse = "|")
      substr(digest$digest(match_str, algo="md5", serialize = FALSE), 1, 15)
    }
  )

  out <- .df
  out[["match_id"]] <- match_id
  out
}
