box::use(here, dplyr)
load(here$here("mod", "data", "babelonplus.rda"))

# bp_order 1-7 identify "core" columns for match_id generation
bp_core <- dplyr$filter(babelonplus, .data$order <= 7)


#' Calculate `match_id`
#'
#' `match_id` is a unique identifier for core columns of babelon & babelonplus
#' translation records. It is generated by concatenating core column data
#' followed by md5 hashing, with the final hash truncated to 15 characters. This
#' ensures that the same set of core date will always produce the same
#' `match_id`.
#'
#' @param .df A babelon- or babelonplus-compatible data.frame.
#' @returns The input data frame with an additional `match_id` column containing
#' a 15-character ID.
#'
#' @section Core Columns:
#' The following columns are currently considered among the core set and are
#' used to generate `match_id`:
#' `r paste0("* ", bp_core, collapse = "\n")`
#'
#' @md
#' @export
calc_match_id <- function(.df) {
  box::use(
    digest, dplyr, purrr, stringr, tidyr,
    ./general
  )

  # cols to expand to URIs
  uri_cols <- dplyr$filter(
    bp_core,
    stringr$str_detect(.data$datatype, "uri")
  )$col

  match_df <- dplyr$select(.df, dplyr$all_of(bp_core$col)) |>
    dplyr$mutate(
      dplyr$across(dplyr$all_of(uri_cols), ~ general$uri_curie(.x, to = "uri"))
    )

  missing <- purrr::pmap_lgl(match_df, function(...) { any(is.na(c(...))) })
  if (any(missing)) {
    n <- sum(missing)
    if (n > 10) {
      n_list <- paste0(
        paste0(c(which(missing)[1:10]), collapse = ", "),
        " (+", n - 10, " more)"
      )
    } else {
      n_list <- paste0(which(missing), collapse = ", ")
    }
    stop(
      "Cannot calculate match_id. Core columns contain NA values in row(s): ",
      n_list
    )
  }

  match_id <- purrr$pmap_chr(
    match_df,
    function(...) {
      match_str <- paste0(c(...), collapse = "|")
      substr(digest$digest(match_str, algo="md5", serialize = FALSE), 1, 15)
    }
  )

  out <- .df
  out[["match_id"]] <- match_id
  out
}
