#' Create Initial GS Translation Review
#'
#' Create a Google Sheets review file for comparing the translation of English
#' to Spanish (español) data. The review file will contain 3 sheets, one for
#' each type of data (label, definition, synonym) and will include columns for
#' Google Translate formulas in both directions.
#'
#' @param en_es_file Path to a CSV file with English and Spanish data columns.
#' @inheritParams write_gs_review
#'
#' @returns List with information to access the new GS review, including `gs`
#' and the names of the 3 sheets created, invisibly.
#'
#' @md
#' @export
create_gs_review <- function(en_es_file, gs, ss_prefix = NULL) {
  box::use(dplyr, purrr, readr)

  en_es <- readr$read_csv(en_es_file, col_types = "c")

  col_present <- col_en_es[names(col_en_es) %in% names(en_es)]

  df_split <- purrr$map2(
    names(col_present),
    col_present,
    ~ dplyr$select(en_es, dplyr$all_of(c("class", .x, "clase", .y))) |>
      dplyr$filter(!dplyr$if_all(c(.x, .y), is.na)) |>
      add_gs_translate_cols()
  )

  write_gs_review(df_split, gs, ss_prefix)
}


#' Write Review Data to Google Sheets
#'
#' Write the review data to Google Sheets, with one sheet per type of data
#' (label, definition, synonym).
#'
#' @param df_list List of 3 `tibble`s with label, definition, and synonym in
#' both Spanish & English.
#' @param gs URL to google sheet or another identifier recognizable by
#' [googledrive::as_id()].
#' @param ss_prefix (OPTIONAL) A prefix to append before "en_es" & the column
#' name when deriving a sheet name for the output.
#'
#' Example:
#' - prefix = "disorder"
#' - column in data.frame that matches `col_en_es` = "definition"
#' - sheet name would become "disorder_en_es_definition"
#'
#' @returns List with information to access the GS review, including `gs` and
#' the names of the 3 sheets created, invisibly.
#'
#' @md
#' @export
write_gs_review <- function(df_list, gs, ss_prefix = NULL) {
  box::use(purrr)

  ss_nm <- purrr$map_chr(df_list, ~ write_gs_review_df(.x, gs, ss_prefix))

  invisible(list(gs = gs, ss = ss_nm))
}


write_gs_review_df <- function(.df, gs, ss_prefix = NULL) {
  box::use(googlesheets4)

  col_present <- col_en_es[names(col_en_es) %in% names(.df)]
  ss_nm <- paste(ss_prefix, "en_es", names(col_present), sep = "_")

  googlesheets4$write_sheet(data = .df, ss = gs, sheet = ss_nm)

  invisible(ss_nm)
}


#' Read Initialized GS Translation Review
#'
#' Read the Google Sheets review file created by `create_gs_review()` (data
#' may have been updated since the initial creation).
#'
#' @inheritParams create_gs_review
#' @returns List of 3 `tibble`s with label, definition, and synonym translation
#' information.
#'
#' @md
#' @export
read_gs_review <- function(gs, ss_prefix = NULL) {
  box::use(googlesheets4, purrr)

  col_present <- names(col_en_es)
  ss_nm <- paste(ss_prefix, "en_es", col_present, sep = "_")

  purrr$map(
    ss_nm,
    ~ googlesheets4$with_gs4_quiet(
        googlesheets4$read_sheet(ss = gs, sheet = .x)
      )
  ) |>
    purrr$set_names(col_present)
}


#' Automatically Review GS Translation Data
#'
#' Automatically compare the English to Spanish human and Google translations
#' and the backtranslation of the human-translated Spanish to English by
#' Google Translate.
#'
#' @param .df A tibble with English and Spanish data columns, as generated by
#' [create_gs_review()].
#' @param cutoff The minimum `match_rating_overall` value to consider a
#' translation to be "passed" (default: 0.75), i.e. of high enough quality to
#' require only minimal human review. See the return values for information
#' about `match_rating_overall`.
#' @param alignment (OPTIONAL) A string indicating the language(s) for which to
#' create a global alignment between matches, could make review easier. `"none"`
#' (default) = no alignment, `"en"` = English, `"es"` = Spanish, `"both"` =
#' both.
#'
#' @returns A tibble with the following 9-11 columns added:
#'
#' * `match_en`: Transformation set needed to create a match between
#' original English & Google backtranslation from TSG Spanish. See
#' [str_compare_all()] for details.
#'
#' * `match_es`: Transformation set needed to create a match between
#' TSG & Google translations.
#'
#' * `match_rating_en`: Rating of the match in `match_en` (0-1; 1 = best). See
#' [rate_comparison()] for calculation details.
#'
#' * `match_rating_es`: Rating of the match in `match_es` (0-1; 1 = best).
#'
#' * `match_rating_overall`: Average of `match_rating_en` and `match_rating_es`.
#'
#' * `<spanish_data_col>_passed`: Values from the Spanish data column that
#' passed the match rating cutoff.
#'
#' * `<spanish_data_col>_final`: Empty column for manual curation of a final
#' translation. It is only necessary to curate a "final" translation if the
#' "passed" translation is not sufficient or missing. It should generally be
#' left empty if it is sufficient.
#'
#' * `final_reviewer`: Empty column for adding identifier for the person who
#' created updated text in the `<spanish_data_col>_final` column. It _may_ be
#' left empty if the "passed" translation is sufficient or when the original
#' translation is used without modification.
#'
#' * `review_notes`: Empty column for free form reviewer notes.
#'
#' If alignment is specified columns named en_align and es_align will be added
#' after the corresponding match_rating columns.
#'
#' @md
#' @export
auto_review_df <- function(.df, cutoff = 0.75, alignment = "none") {
  box::use(
    dplyr, pwalign,
    ./rate, ./similar,
  )

  alignment <- match.arg(alignment, c("none", "en", "es", "both"))

  # automatically identify original English & Spanish columns in .df
  # (name-based -- label, definition, or synonym)
  col_nm <- col_en_es[names(col_en_es) %in% names(.df)]

  out <- .df |>
    dplyr$mutate(
      # compare strings
      match_en = similar$str_compare_all(
        .data[[names(col_nm)]],
        .data$google_translate_to_en
      ),
      match_es = similar$str_compare_all(
        .data[[col_nm]],
        .data$google_translate_to_es,
        locale = "es"
      ),
      # rate translation matches (hopefully related to quality)
      match_rating_en = rate$rate_comparison(.data$match_en),
      match_rating_es = rate$rate_comparison(.data$match_es),
      # calculate overall match rating (mean)
      match_rating_overall = (match_rating_en + match_rating_es) / 2,
      # if match score above cutoff, copy TSG translation to "passed"
      "{col_nm}_passed" := dplyr$if_else(
        match_rating_overall > cutoff,
        .data[[col_nm]],
        NA_character_
      ),
      # add column for final translation
      "{col_nm}_final" := NA_character_,
      # add columns for curator review
      final_reviewer = NA_character_,
      review_notes = NA_character_
    )

  # add alignment columns as specified
  if (alignment == "both") alignment <- c("en", "es")

  if ("en" %in% alignment) {
    g_align <- pwalign$pairwiseAlignment(
      out[[names(col_nm)]],
      out[["google_translate_to_en"]],
      type = "global"
    )

    out <- dplyr$mutate(
      out,
      en_align = paste0(
        as.character(pwalign$alignedPattern(g_align)), "\n",
        as.character(pwalign$alignedSubject(g_align))
      ),
      .before = .data[["match_en"]]
    )
  }

  if ("es" %in% alignment) {
    g_align <- pwalign$pairwiseAlignment(
      out[[col_nm]],
      out[["google_translate_to_es"]],
      type = "global"
    )

    out <- dplyr$mutate(
      out,
      es_align = paste0(
        as.character(pwalign$alignedPattern(g_align)), "\n",
        as.character(pwalign$alignedSubject(g_align))
      ),
      .before = .data[["match_es"]]
    )
  }

  out
}


#' @inheritParams read_gs_review
#' @param overwrite Whether to overwrite the original review file with the
#' updated data (default: `FALSE`).
#'
#' @returns A list of tibbles as described in [auto_review_df()].
#'
#' @rdname auto_review_df
#' @export
auto_review <- function(gs, ss_prefix = NULL, cutoff = 0.75, alignment = "none",
                        overwrite = FALSE) {
  box::use(purrr)

  review <- read_gs_review(gs, ss_prefix)
  out <- purrr$map(
    review,
    ~ auto_review_df(.x, cutoff = cutoff, alignment = alignment)
  )

  if (overwrite) write_gs_review(out, gs, ss_prefix)

  out
}


#' Finalize GS Translation Review
#'
#' Finalize the review of the Google Sheets translation data after manual review
#' and establishment of final translations by comparing the final translations
#' to the prior Spanish translations.
#'
#' @param .df A tibble including English and Spanish data columns, as generated
#' by [create_gs_review()] and [auto_review_df()], and after manual review of
#' the `*_passed` column, with changes in the `*_final` column and the reviewer
#' identified in `final_reviewer`.
#' @inheritParams str_compare_all_list
#'
#' @md
#' @export
finalize_review_df <- function(.df, how = "all", delim = "|",
                                 locale = "en", stopwords = NULL,
                                 input_delim = "\n", ...) {
  box::use(
    dplyr, tidyr,
    ./similar
  )

  cols <- col_en_es[names(col_en_es) %in% names(.df)]
  col <- list()
  col$en <- names(cols)
  col$es <- unname(cols)
  col$passed <- paste0(col$es, "_passed")
  col$final <- paste0(col$es, "_final")

  out <- .df |>
    dplyr$mutate(
      final_diff = similar$str_compare_all_list(
        .data[[col$final]],
        dplyr$pick(
          .data[[col$passed]], .data[[col$es]], .data$google_translate_to_es
        ),
        how = how, delim = delim, locale = locale, stopwords = stopwords,
        input_delim = input_delim,
        ...
      )
    )

  out
}

#' @inheritParams read_gs_review
#' @param overwrite Whether to overwrite the original review file with the
#' updated data (default: `FALSE`).
#'
#' @returns A list of tibbles as described in [finalize_review_df()].
#'
#' @rdname finalize_review_df
#' @export
finalize_review <- function(gs, ss_prefix = NULL, overwrite = FALSE) {
  box::use(purrr)

  review <- read_gs_review(gs, ss_prefix)
  # only finalize those with values in the final_* column
  ready <- purrr$map_lgl(
    review,
    function(.df) {
      cols <- col_en_es[names(col_en_es) %in% names(.df)]
       col_final <- paste0(unname(cols), "_final")

      any(!is.na(.x[[col_final]]))
    }
  )
  out <- list()
  out[!ready] <- review[!ready]
  if (any(ready)) {
    out[ready] <- purrr$map(review[ready], review_finalize_df)
  }

  if (overwrite) write_gs_review(out, gs, ss_prefix)

  out
}


#' Standardize GS Translation Review
#'
#' Standardizes GS Translation Reviews to the format designed for tab-delimited
#' data files that will serve for comparison against the data in the ontology,
#' to identify changes, and for data loading into the ontology via a robot
#' template.
#'
#' @param .df A tibble including English and Spanish data columns, as generated
#' by [create_gs_review()], [auto_review_df()], and human curation of the
#' `*_final` column.
#'
#' @export
standardize_review_df <- function(.df, lang = "es") {
  box::use(
    dplyr, tidyr,
    . / similar
  )

  col_present <- names(col_en_es) %in% names(.df)
  col_en <- names(col_en_es[col_present])
  col_es <- unname(col_en_es[col_present])
  passed_col <- paste0(col_es, "_passed")
  final_col <- paste0(col_es, "_final")

  out <- .df |>
    dplyr$mutate(
      predicate = "rdfs:label",
      # fill *_final columns with *_passed or TSG values, where empty
      translation_text = dplyr$case_when(
        !is.na(.data[[final_col]]) ~ .data[[final_col]],
        !is.na(.data[[passed_col]]) ~ .data[[passed_col]],
        TRUE ~ .data[[col_es]]
      ),
      translator = "The Spanish Group (https://thespanishgroup.org/)",
      # translation_review = dplyr::case_when(
      #   !is.na(.data[[final_col]]) ~ "manual",
      source_lang = "en",
      translation_lang = lang,
      status = dplyr$case_when(
        !is.na(.data[[final_col]]) ~ "final",
        !is.na(.data[[passed_col]]) ~ "passed automated review",
        !is.na(.data[[col_es]]) ~ "manually translated",
        TRUE ~ NA_character_
      )
    ) |>
    dplyr$select(
      source_id = "class", "predicate", source_text = dplyr::all_of(col_en),
      "translation_text", "translator", "source_lang", "translation_lang",
      "status", auto_review_score = "match_rating_overall", "final_reviewer",
      "review_notes"
    )
  out
}

#' @inheritParams read_gs_review
#' @param overwrite Whether to overwrite the original review file with the
#' updated data (default: `FALSE`).
#'
#' @returns A list of tibbles as described in [standardize_review_df()].
#'
#' @rdname standardize_review_df
#' @export
standardize_review <- function(gs, ss_prefix = NULL, overwrite = FALSE) {
  box::use(purrr)

  review <- read_gs_review(gs, ss_prefix)
  # only finalize those with values in the final_* column
  ready <- purrr$map_lgl(
    review,
    function(.df) {
      cols <- col_en_es[names(col_en_es) %in% names(.df)]
      col_final <- paste0(unname(cols), "_final")

      any(!is.na(.x[[col_final]]))
    }
  )
  out <- list()
  out[!ready] <- review[!ready]
  if (any(ready)) {
    out[ready] <- purrr$map(review[ready], review_finalize_df)
  }

  if (overwrite) write_gs_review(out, gs, ss_prefix)

  out
}


### GENERAL gs_review helpers ################################################

#' Full Column Names
#'
#' Full column names for English and Spanish (English = names, Spanish = values).
col_en_es <- c(
  "label" = "etiqueta", "definition" = "definición", "synonym" = "sinónimo"
)


### create_gs_review() helpers ###############################################

#' Add GS Translation Columns
#'
#' Adds columns with Google Sheets formulas to calculate translation in both
#' directions (one column each) using the GOOGLTRANSLATE function.
#'
#' @section REQUIRED:
#' Input must have 4 columns in a set order. The order is "class", a column with
#' a single type of English data directly from DO (label, definition, or
#' synonym), "clase", and a column with the Spanish translation by "The Spanish
#' Group" (TSG) corresponding to the English data (etiqueta, definición, or
#' sinónimo).
add_gs_translate_cols <- function(df) {
  box::use(dplyr, glue, googlesheets4)

  df |>
    dplyr$mutate(
      google_translate_to_en = googlesheets4$gs4_formula(
        glue$glue(
          '=GOOGLETRANSLATE({cell_ref}, "es", "en")',
          cell_ref = form_cell_ref("E")
        )
      ),
      .after = 2
    ) |>
    dplyr$mutate(
      google_translate_to_es = googlesheets4$gs4_formula(
         glue(
          '=GOOGLETRANSLATE({cell_ref}, "en", "es")',
          cell_ref = form_cell_ref("C")
        )
      ),
      .after = dplyr$last_col()
    )
}

#' Form GS Cell References
#'
#' Form cell references using specified column input (letter) and row numbers,
#' as they will appear in google sheet.
#'
#' @param col_letter The column letter to use in the cell reference.
#' @param w_title Whether a title row will be present in the sheet (default:
#' `TRUE`). _Adjusts row numbers down 1._
form_cell_ref <- function(col_letter, w_title = TRUE) {
  box::use(dplyr)

  if (w_title) {
    paste0(col_letter, dplyr$row_number() + 1)
  } else {
    paste0(col_letter, dplyr$row_number())
  }
}


### read_gs_review() helpers #################################################

#' Automatically Identify & Read TSV/CSV files
#'
#' A light wrapper around [readr::read_delim()] that automatically identifies
#' the delimiter based on file extension (can include compression extensions).
#'
#' Note that this function is primarily intended for internal use; therefore,
#' messages about guessed column types are not generated.
#'
#' @param file The path to a csv/tsv file or connection.
#'
#' Files ending in `.gz`, `.bz2`, `.xz`, or `.zip` will be automatically
#' uncompressed. Files starting with `http://`, `https://`, `ftp://`, or
#' or `ftps://` will be automatically downloaded.
#'
#' @inheritParams readr::read_delim
#' @inheritDotParams readr::read_delim -delim -quoted_na
read_delim_auto <- function(file, ..., show_col_types = FALSE) {
  ext <- stringr$str_match(file, "\\.([tc]sv)(\\.(gz|bz2|xz|zip))?")[, 2]
  delim <- switch(ext, tsv = "\t", csv = ",")
  if (is.null(delim)) stop("`file` must have .tsv or .csv extension.")

  box::use(readr, stringr)

  readr$read_delim(
    file = file,
    delim = delim,
    show_col_types = show_col_types,
    ...
  )
}
